export default {
    扩展条件:'Extended conditions',
    删除:'Delete',
    添加:'Add',
    是:'Yes',
    否:'No',
    编辑:'Edit',
    复制:'copy',
    富文本:'Rich text',
    上传图片:'Upload image',
    选取文件:'Select file',
    取消:'Cancel',
    立即上传:'Upload now',
    立即插入:'Insert now',
    最近一周:'Last week',
    最近一个月:'Last month',
    最近三个月:'Last three months',
    开始日期:'Start date',
    结束日期:'End date',
    图片路径:'Image path',
    上传失败:'Upload failed',
    保存成功:'Save successfully',
    请上传:'Please upload',
    请输入:'Please enter',
    属性名:'Attribute name',
    条件:'Condition',
    数值:'Value',
    操作:'Operation',
    保存:'Save',
    确认删除:'Confirm deletion',
    确定:'Confirm',
    删除成功:'Delete successfully',
    平铺排序:'Tile sorting',
    提示:'Prompt',
    查询:'Query',
    导出:'Export',
    选择时间:'Select time',
    选择日期:'Select date',
}
